### ISSUE TITLE
doc issues

### ISSUE THREAD

**Issue by brentp** [gogetdata/ggd-cli#17]
+ [x] a detailed figure should not be in a "quick-start" section. In quickstart, show a few command-line examples. Save the image for a more detailed section
+ [x] the section indicating how to install should be titled "Installation" and made a super-heading closer to the top of the document.
+ [x] readme for ggd-cli and ggd-recipes should be updated to point to or match whats in gogetdata.github.io
+ [ ] the contents appears under "Contributing" it should be its own header and should be only 1 level deep (so we see each command, not example and "Using ..." for each command. Or, the contents section may be removed.
+ [ ] not clear how the icons adn the columns interact on this page: https://gogetdata.github.io/recipes.html (e.g. why do we need a linux column, and a linux icon). I recipe is either OSX, Linux or noarch, so why not have a single "arch" column?

**Comment by mikecormier** [comment]
@brentp, can you have another look at the docs? Any new suggestions?

**Comment by brentp** [comment]
this looks very nice to me. I still don't see the utility of the icons on the recipe page, but that's a minor thing.
