### ISSUE TITLE
env_vars.sh cleanup

### ISSUE THREAD

**Issue by jbelyeu** [gogetdata/ggd-cli#2]
When installing a recipe a new environment variable is appended to conda_root/etc/conda/activate.d/env_vars.sh and conda_root/etc/conda/deactivate.d/env_vars.sh. Since this is only appended, old copies of vars will be maintained in the file. In the interest of neatness, we should remove old var declarations from these files on adding a new one.

**Comment by mikecormier** [comment]
This is now implemented during the `ggd uninstall` phase.
