### ISSUE TITLE
Should installed recipe versions be removed when a different version is installed?

### ISSUE THREAD

**Issue by jbelyeu** [gogetdata/ggd-cli#5]
Adding the option of maintaining different versions of recipes means there could be multiple versions of a dataset installed at once. We could use a post-link script (http://conda.pydata.org/docs/building/build-scripts.html) to handle this by removing old versions. We could also maintain those other versions (updating the environment variable to the most recently installed version) and allow them to be access via the ggd list-files command.

**Comment by mikecormier** [comment]
Closing this issue. I believe we have a solution to the problem implemented.
