### ISSUE TITLE
Version coordination

### ISSUE THREAD

**Issue by jbelyeu** [gogetdata/ggd-cli#8]
Versions are supported now in recipe installation. The version number (which allows a string but not whitespace) is parsed out of the meta.yaml file by check-recipe and included in the installation directory structure. This needs to be thought out more fully, however. The environment variables created by prelink.sh don't all include the version number currently and there may be additional issues caused by inclusion of the version number that I haven't thought of yet.

**Comment by jbelyeu** [comment]
list-files needs to be double-checked as well. A version argument has been added to it and default behavior expands the directory for each version, so it might be fine, but it should be reviewed

**Comment by brentp** [comment]
nice!

 if you install a different version of a recipe, conda should uninstall a different version on its own. so we shouldn't need the number in the env variable.

**Comment by jbelyeu** [comment]
Good point...we should test and make sure that actually works, then. We might also need to more fully establish exactly what we want from the version information, because I think I still don't completely get it and current implementation is bound to reflect that.

**Comment by jbelyeu** [comment]
Just to confirm, I reviewed the build and version numbers are currently being included in the installation directory structure and seem to be working fine. The list-files and environment variables both work with the correct path (including the version), but the environment variable _name_ does not have the version, as it most likely should not. We'll need to change that if we decide to support multiple concurrent versions of the same package.
